export const BOOKS = [
  { label: 'Genesis', value: 'Genesis ' },
  { label: 'Exodus', value: 'Exodus ' },
  { label: 'Leviticus', value: 'Leviticus ' },
  { label: 'Numbers', value: 'Numbers ' },
  { label: 'Deuteronomy', value: 'Deuterpnomy ' },
  { label: 'Joshua', value: 'Joshua ' },
  { label: 'Judges', value: 'Judges ' },
  { label: 'Ruth', value: 'Ruth ' },
  { label: '1 Samuel', value: '1 Samuel ' },
  { label: '2 Samuel', value: '2 Samuel ' },
  { label: '1 Kings', value: '1 Kings ' },
  { label: '2 Kings', value: '2 Kings ' },
  { label: '1 Chronicles', value: '1 Chronicles ' },
  { label: '2 Chronicles', value: '2 Chronicles ' },
  { label: 'Ezra', value: 'Ezra ' },
  { label: 'Nehemiah', value: 'Nehemiah ' },
  { label: 'Esther', value: 'Esther ' },
  { label: 'Job', value: 'Job ' },
  { label: 'Psalms', value: 'Psalms ' },
  { label: 'Proverbs', value: 'Proverbs ' },
  { label: 'Song of Solomon', value: 'Song of Solomon ' },
  { label: 'Isaiah', value: 'Isaiah ' },
  { label: 'Jeremiah', value: 'Jeremiah ' },
  { label: 'Lamentations', value: 'Lamentations ' },
  { label: 'Ezekiel', value: 'Ezekiel ' },
  { label: 'Daniel', value: 'Daniel ' },
  { label: 'Hosea', value: 'Hosea ' },
  { label: 'Joel', value: 'Joel ' },
  { label: 'Amos', value: 'Amos ' },
  { label: 'Obadiah', value: 'Obadiah ' },
  { label: 'Jonah', value: 'Jonah ' },
  { label: 'Micah', value: 'Micah ' },
  { label: 'Nahum', value: 'Nahum ' },
  { label: 'Habakkuk', value: 'Habakkuk ' },
  { label: 'Zephaniah', value: 'Zephaniah ' },
  { label: 'Haggai', value: 'Haggai ' },
  { label: 'Zechariah', value: 'Zechariah ' },
  { label: 'Malachi', value: 'Malachi ' },
  { label: 'Matthew', value: 'Matthew ' },
  { label: 'Mark', value: 'Mark ' },
  { label: 'Luke', value: 'Luke ' },
  { label: 'John', value: 'John ' },
  { label: 'Acts', value: 'Acts ' },
  { label: 'Romans', value: 'Romans ' },
  { label: '1 Corinthians', value: '1 Corinthians ' },
  { label: '2 Corinthians', value: '2 Corinthians ' },
  { label: 'Galatians', value: 'Galatians ' },
  { label: 'Ephesians', value: 'Ephesians ' },
  { label: 'Philippians', value: 'Philippians ' },
  { label: 'Colossians', value: 'Colossians ' },
  { label: '1 Thessalonians', value: '1 Thessalonians ' },
  { label: '2 Thessalonians', value: '2 Thessalonians ' },
  { label: '1 Timothy', value: '1 Timothy ' },
  { label: '2 Timothy', value: '2 Timothy ' },
  { label: 'Titus', value: 'Titus ' },
  { label: 'Philemon', value: 'Philemon ' },
  { label: 'Hebrews', value: 'Hebrews ' },
  { label: 'James', value: 'James ' },
  { label: '1 Peter', value: '1 Peter ' },
  { label: '2 Peter', value: '2 Peter ' },
  { label: '1 John', value: '1 John ' },
  { label: '2 John', value: '2 John ' },
  { label: '3 John', value: '3 John ' },
  { label: 'Jude', value: 'Jude ' },
  { label: 'Revelation', value: 'Revelation ' },
];
